---
type: showroom

default_width: 30
persist_url_state: true

view_switcher:
  enabled: true
  default_mode: content

tabs:
  - name: Developer Hub
    url: '/modules/open-developer-hub.html'
  - name: Terminal
    url: '/terminal/'
